const menu = [
  {
    id: 1,
    img: "https://media.easemytrip.com/media/Blog/India/636969766251686038/636969766251686038e7QQhQ.jpg",
    name: "Dahi Paratha",
    desc: "Relishing Breakfast Dishes Famous in Varied Indian States",
    category: "Breakfast",
    class: "",
    price: "Rs. 150/-",
    cart: "none",
  },
  {
    id: 2,
    img: "https://ddakzuk4yih5h.cloudfront.net/Recipe-categories/cookie-category.jpg",
    name: "Cookies",
    desc: "Tender cookie pillows, filled with a delicious walnut mixture.",
    category: "Breakfast",
    class: "",
    price: "Rs. 80/-",
    cart: "none",
  },
  {
    id: 3,
    img: "https://content.jdmagicbox.com/comp/sahibabad/n8/011pxx11.xx11.190207200724.s6n8/catalogue/solo-food-point-sahibabad-sahibabad-street-food-5cigkdlurd.jpg",
    name: "Chole Bhature",
    desc: "Spicy and Tasty Indian Dish",
    category: "Dinner",
    class: "",
    price: "Rs. 200/-",
    cart: "none",
  },
  {
    id: 4,
    img: "https://pbs.twimg.com/media/DXC6X27VAAET8OU.jpg",
    name: "Dora Cake",
    desc: "Famous Japanese Dish, delicious and sweet in taste, favorite of Doraemon",
    category: "Breakfast",
    class: "",
    price: "Rs. 100/-",
    cart: "none",
  },
  {
    id: 5,
    img: "https://cdn.lifestyleasia.com/wp-content/uploads/sites/6/2020/10/15130549/Solo-Ristorante-Tagliolini-min-min-scaled.jpg",
    name: "Italian Rolled Pasta",
    desc: "Italian Spicy Rolled Pasta",
    category: "Breakfast",
    class: "",
    price: "Rs. 500/-",
    cart: "none",
  },
  {
    id: 6,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYu6lMPOzzSf56IbWSYioOgquWvvmb3ZUVwg&usqp=CAU",
    name: "Cheese Franky",
    desc: "Indian Spicy Rolled Cheesy Chapati",
    category: "Lunch",
    class: "",
    price: "Rs. 80/-",
    cart: "none",
  },
  {
    id: 7,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR36OaQVVLrQjbQ9iy6nCAehQ-Yj7ZhYGkBu_SFpSN5eU7KccEjNz9DQ67nNIJBImgiT3c&usqp=CAU",
    name: "Chicken",
    desc: "Famous Indian Spicy Chicken",
    category: "Dinner",
    class: "",
    price: "Rs. 800/-",
    cart: "none",
  },
  {
    id: 8,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQCw_i39fgrM2i063SmDS7TaiqPEzIO01NZg&usqp=CAU",
    name: "Gulaab Jamun",
    desc: "Sweet and Delicious",
    category: "Dinner",
    class: "",
    price: "Rs. 100/-",
    cart: "none",
  },
  {
    id: 9,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQYLJr1MFXOUMZsSTf-Fe0Rx4Bw2cgitS_PQ&usqp=CAU",
    name: "Spicy Chicken Fried Rice",
    desc: "Non-veg Fried Chicken Rice with Cheese",
    category: "Dinner",
    class: "",
    price: "Rs. 1000/-",
    cart: "none",
  },
  {
    id: 10,
    img: "https://i2.wp.com/themagzone.com/wp-content/uploads/2017/04/jalebi.jpeg?fit=1050%2C600&ssl=1",
    name: "Jalebi",
    desc: "Famous Indian Sweet",
    category: "Breakfast",
    class: "",
    price: "Rs. 100/-",
    cart: "none",
  },
  {
    id: 11,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1IZGrCo0qIu-uIv8IaiNSq4RIwYjxY1FSwQ&usqp=CAU",
    name: "Dosa Sambhar",
    desc: "South Indian Dish",
    category: "Dinner",
    class: "",
    price: "Rs. 250/-",
    cart: "none",
  },
  {
    id: 12,
    img: "https://deih43ym53wif.cloudfront.net/idly-food-india-shutterstock_101041240_7bd8a6703f.jpeg",
    name: "Idli Sambhar",
    desc: "South Indian Dish",
    category: "Dinner",
    class: "",
    price: "Rs. 250/-",
    cart: "none",
  },
  {
    id: 13,
    img: "https://static.westernunion-microsites.com/blog/uploads/2019/08/Gol-Gappe-300x205.jpg",
    name: "Pani Puri",
    desc: "Indian Street Food, spicy and delicious",
    category: "Lunch",
    class: "",
    price: "Rs. 100/-",
    cart: "none",
  },
  {
    id: 14,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoGFq5KW5nnyDpVM23Gx1K7v5tnlG7VZ9DMvNStLbrzzsTdnu97gHVPzKMxYBAZJD4pZY&usqp=CAU",
    name: "Samosa",
    desc: "Spicy Triangular Indian Food",
    category: "Lunch",
    class: "",
    price: "Rs. 50/-",
    cart: "none",
  },
  {
    id: 15,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCY7DAn5PEPjifWNAjEIaXdtvYr_oQ9iiXAQ&usqp=CAU",
    name: "Dabeli",
    desc: "Dabeli is an Indian Food similar to Burger but tastier than that!",
    category: "Lunch",
    class: "",
    price: "Rs. 80/-",
    cart: "none",
  },
  {
    id: 16,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnVVRXnAUpOIz7PuvjWOZsmIR9q3WAbDJhlg&usqp=CAU",
    name: "Vada",
    desc: "Mumbai Signature Food!",
    category: "Lunch",
    class: "",
    price: "Rs. 50/-",
    cart: "none",
  },
];

export default menu;
